### PR TITLE
TV show Application

### PR DESCRIPTION
**Pull request by anyepeter**
# TV show Application
 The entire application is setup with the following requirements 📑 

## General requirements
✅ Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
✅ Make sure that you used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
✅ Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
## HTML/CSS & JavaScript requirements
✅ Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
✅ Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

## Project requirements

✅ First, you need to find an API so you can base the development of the webapp around it. The API should allow you to:

   ✅ Get a list of items with a unique item id (or generate the unique id).
   ✅For a given item, get detailed information about it.

✅We choose the [TVmaze API](https://www.tvmaze.com/api): data about TV series and movies.

✅ You will use our [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to record the different user interactions (likes, comments and reservations).
Interfaces

- We built these interfaces:
    ✅The home page.
    ✅The comments popup.
    ✅The reservations popup (only for the groups of 3 students).

✅ We follow the layout of the wireframes provided. We personalize the rest of the design including colors, typographies, spacings, etc.

- Home page
    When the page loads, the webapp retrieves data from:
       ✅The selected API and shows the list of items on screen.
       ✅The Involvement API to show the item likes.

    Remember that your page should make only 2 requests:
       ✅One to the base API.
       ✅And one to the Involvement API.

   When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
      ✅When the user clicks on the "Comments" button, the Comments popup appears.
When the user clicks on the "Reservations" button, the Reservations popup appears (only for the groups of 3 students).
      ✅Home page header and navigation similar to the given mockup.
      ✅Home page footer similar to the given mockup.

- Comments popup
     ✅ When the popup loads, the webapp retrieves data from:
     ✅The selected API and shows details about the selected item.
     ✅The Involvement API to show the item comments.
     ✅When the user clicks on the "Comment" button, the data is recorded in the Involvement API and the screen is updated.

- Reservations popup
     ✅When the popup loads, the webapp retrieves data from:
     ✅The selected API and shows details about the selected item.
     ✅The Involvement API to show the item reservations.
     ✅When the user clicks on the "Reserve" button, the data is recorded in the Involvement API and the screen is updated.

- Counters We have counters in all the interfaces that show:

   ✅The number of items (home).
   ✅The number of comments (comments popup).
   ✅The number of reservations (reservations popup)
   ✅Even if the API gives you these numbers, you will create a specific function to calculate these numbers in each page. These count functions need to be covered with unit tests using Jest.

### Technical set up

✅ Set up the repository on GitHub and use Gitflow.
✅ Set up webpack.
✅Set up a JavaScript testing library (Jest).

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello Team 👋🏽 

Good job working on the project so far! 
✔️ No linter errors
✔️ The design template was followed
However, there are some issues that you need to work on to go to the next project but you are almost there!



## Required Changes ♻️
- [ ] Kindly add more tests to your project to ensure it covers all edge cases. Also as per the requirements, think about a scenario in which there are 0 items on the page (counter function should return 0) and add tests for it.
- [ ] Great video explaining your project, however, according to the requirements, please state a piece of the code that you find interesting or are proud of making.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- I suggest that when working with APIs, a separate module is created for its implementation where the base URL and other URLs are clearly defined as this improves the readability of the code.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by anyepeter** [comment]
@Ghiftee Thanks very much for your review we really do appreciate it and we will adjust the various changes 😊

**Comment by anyepeter** [comment]
We adjusted the project due to the required of the last code reviewer. We added the test cases and record a new video.

**Review by alexander16108 — APPROVED** [review]
Hi @anyepeter  and @Ghiftee  and @Abe1able , 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 




Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by AbayomiOlaoye** [comment]
Great job, team! 🎉

**Pull request merged**
